sudo: required

dist: trusty

language: c

complier:
    gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - doxygen
            - doxygen-doc
            - lcov

matrix:
    include:
        - os: linux

install:
    #- git lfs pull
    - source .ci/travis.sh
    - pip install coveralls

cache:
    directories:
        - $HOME/miniconda
        - .git/lfs

git:
    # https://github.com/travis-ci/travis-ci/issues/8787#issuecomment-394202791
    lfs_skip_smudge: true

script:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make coverage; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then py.test; fi


after_success:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then coveralls --verbose; fi
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then source .ci/build-docs.sh; fi
