sudo: required

dist: trusty

language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - doxygen
            - doxygen-doc
            - lcov

matrix:
    include:
        - os: linux

install:
    - source .ci/travis.sh

cache:
    directories:
        - $HOME/miniconda

script:
    - py.test -v -s tests

after_success:
    - make coverage
    # DEBUG: switch to `master` below
    - if [ "$TRAVIS_BRANCH" = "dev" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-docs.sh; fi
