name: docs

on:
  push:
    branches: [master, pip] # TODO: Remove pip

jobs:
  tests:
    name: "Build docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        id: setup_python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vplanet
          environment-file: environment.yml

      - name: Install
        id: install
        if: steps.setup_python.outcome == 'success'
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e .

      - name: Build
        id: build
        if: steps.install.outcome == 'success'
        shell: bash -l {0}
        run: |
          cd docs
          make html
          cp sphinx_rtd_theme/static/css/theme.css .build/html/_static/css/theme.css
          touch .build/html/.nojekyll

      - uses: JamesIves/github-pages-deploy-action@4.1.2
        if: steps.build.outcome == 'success'
        with:
          branch: gh-pages
          folder: docs/.build/html
          dry-run: true